Update codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,49 +1,49 @@
 workflows:
-  android-workflow:
-    name: Android Workflow
+  flutter-android:
+    name: Flutter Android
     max_build_duration: 120
+    instance_type: mac_mini_m2
     environment:
       android_signing:
         - keystore_reference
       groups:
-        - google_play
+        - google_play # Pastikan grup ini mencakup GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
       vars:
-        PACKAGE_NAME: "io.codemagic.fluttersample"
-        GOOGLE_PLAY_TRACK: alpha
-      flutter: stable
+        PACKAGE_NAME: "io.codemagic.sample.flutter" # Ubah sesuai dengan nama paket Anda
+        FLUTTER_VERSION: "stable"
     scripts:
-      - name: Set up local.properties
-        script: | 
-          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
-      - name: Get Flutter packages
-        script: | 
-          flutter packages pub get
-      - name: Flutter analyze
-        script: | 
-          flutter analyze
-      - name: Flutter unit tests
-        script: | 
-          flutter test
-        ignore_failure: true
-      - name: Build AAB with Flutter
-        script: | 
-          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
-          flutter build appbundle --release \
-            --build-name=1.0.$BUILD_NUMBER \
-            --build-number=$BUILD_NUMBER
+      - name: Set up Flutter
+        script: |
+          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.7.0-stable.zip
+          unzip flutter_macos_3.7.0-stable.zip
+          export PATH="$PATH:`pwd`/flutter/bin"
+          flutter doctor
+      - name: Install dependencies
+        script: |
+          flutter pub get
+      - name: Set Android SDK location
+        script: |
+          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
+      - name: Build Android release
+        script: |
+          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+          if [ -z "$LATEST_GOOGLE_PLAY_BUILD_NUMBER" ]; then
+            # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
+            UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+          else
+            UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+          fi
+          flutter build appbundle --build-number=$UPDATED_BUILD_NUMBER --build-name=1.0.$UPDATED_BUILD_NUMBER
     artifacts:
-      - build/**/outputs/**/*.aab
-      - build/**/outputs/**/mapping.txt
-      - flutter_drive.log
+      - build/app/outputs/**/*.aab
     publishing:
       email:
         recipients:
           - user_1@example.com
           - user_2@example.com
         notify:
-          success: true
-          failure: false
+          success: true     # To not receive a notification when a build succeeds
+          failure: false    # To not receive a notification when a build fails
       google_play:
         credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
-        track: $GOOGLE_PLAY_TRACK
-        submit_as_draft: true
+        track: alpha   # Any default or custom track that is not in ‘draft’ status
